### ISSUE TITLE
Incompatability with Botania

### ISSUE THREAD

**Issue by ImperialsGit** [1whohears/DiamondStarCombat#41]
Client crashes on loading stage with Botania installed. Reproducible on 1.19.2, latest version of both mods. 2 versions ago this mod did not have any issues with Botania, now doesn't work with any build of Botania.

[crash-2023-12-27_00.10.35-client.txt](https://github.com/1whohears/DiamondStarCombat/files/13776002/crash-2023-12-27_00.10.35-client.txt)

**Comment by 1whohears** [comment]
Fixed by [0b97fe6](https://github.com/1whohears/DiamondStarCombat/commit/0b97fe67ba6e2a1f32e2a1356e885be1215b03a5). Botania was instantiating a turret item before the weapon data was loaded so all the weapon preset data was null. This used to be accounted for but I was trying to rename certain weapons between versions which created a new edge case. Thank you for the report!
